import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';
import { COLORS } from './utils/colors';

// Get device dimensions for responsive sizing
const { width: SCREEN_WIDTH } = Dimensions.get('window');

// Get safe area top inset - accounts for notch/status bar on different devices
const STATUS_BAR_HEIGHT = Platform.OS === 'ios' ? 50 : StatusBar.currentHeight || 0;

// Responsive horizontal padding based on screen width
// Small devices (< 375): 16px
// Medium devices (375-414): 20px
// Large devices (> 414): 24px
const HORIZONTAL_PADDING = SCREEN_WIDTH < 375 ? 16 : SCREEN_WIDTH > 414 ? 24 : 20;

// Helper function to get Cabinet Grotesk font based on weight
const _getCabinetFont = (weight) => {
  if (weight === 'bold' || weight === '700' || weight === '800' || weight === '900') {
    return 'CabinetGrotesk-Bold';
  } else if (weight === '500' || weight === '600') {
    return 'CabinetGrotesk-Medium';
  }
  return 'CabinetGrotesk-Regular';
};

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: COLORS.DARK_BG,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: HORIZONTAL_PADDING,
    paddingTop: HORIZONTAL_PADDING,
  },
  splashContainer: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogo: {
    width: 152,
    height: 152,
    marginBottom: 20,
  },
  splashTitle: {
    fontSize: 36,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 4,
    letterSpacing: 4,
  },
  splashSubtitle: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    fontWeight: '300',
    color: COLORS.PURPLE,
    letterSpacing: 0,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 0,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 32,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 4,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    fontWeight: '300',
    color: COLORS.PURPLE,
    marginBottom: 32,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  welcomeContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: 0,
    paddingBottom: HORIZONTAL_PADDING,
    backgroundColor: COLORS.DARK_BG,
  },
  welcomeContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  welcomeButtons: {
    width: '100%',
    paddingBottom: HORIZONTAL_PADDING + 20,
  },
  welcomeLogo: {
    width: 120,
    height: 120,
  },
  welcomeTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 8,
    textAlign: 'center',
    fontWeight: 'bold',
    paddingHorizontal: 12,
  },
  welcomeTagline: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 32,
    textAlign: 'center',
    fontWeight: '400',
    paddingHorizontal: 12,
  },
  topAddAccountButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.PRIMARY_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 8,
    width: '100%',
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  resetButton: {
    backgroundColor: COLORS.DANGER_RED,
    marginTop: 32,
  },
  secondaryButton: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginTop: 8,
  },
  walletInfo: {
    width: '100%',
    backgroundColor: COLORS.DARK_BG,
    padding: HORIZONTAL_PADDING,
    marginHorizontal: 0,
    borderRadius: 16,
    marginTop: 4,
  },
  stepIndicator: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  introIconContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  introIcon: {
    fontSize: 60,
    color: COLORS.PRIMARY_BLUE,
  },
  introTitle: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 16,
    textAlign: 'center',
  },
  introText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    lineHeight: 22,
    marginBottom: 32,
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  infoBox: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    padding: 0,
    marginBottom: 32,
  },
  infoTitle: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 12,
  },
  infoItem: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    lineHeight: 28,
    textAlign: 'center',
  },
  infoText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    lineHeight: 22,
  },
  warningText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.DANGER_RED,
    backgroundColor: COLORS.PINK_WHITE,
    padding: 16,
    borderRadius: 8,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  walletTitle: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    flex: 1,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addAccountButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.PRIMARY_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addAccountText: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  addressToggle: {
    flexDirection: 'row',
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 8,
    overflow: 'hidden',
  },
  toggleButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  toggleButtonLeft: {
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  toggleButtonRight: {
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  toggleButtonActive: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  toggleText: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
  },
  toggleTextActive: {
    color: COLORS.VERY_LIGHT_GRAY,
  },
  totalBalanceSection: {
    marginBottom: 32,
  },
  totalBalanceLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 8,
  },
  balanceContainer: {
    minHeight: 44,
    justifyContent: 'center',
  },
  loadingContainer: {
    height: 44,
    justifyContent: 'center',
  },
  totalBalanceAmount: {
    fontSize: 36,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  totalBalanceAmountSmall: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Bold',
  },
  assetsContainer: {
    minHeight: 144,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  assetsScrollContainer: {
    flex: 1,
  },
  assetsScrollContent: {
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingBottom: 0,
  },
  assetCard: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingTop: 12,
    marginBottom: SCREEN_WIDTH <= 375 ? 4 : 12,
    height: 64,
  },
  assetCardLast: {
    marginBottom: 0,
  },
  vaultCard: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 12,
    padding: 16,
    marginBottom: SCREEN_WIDTH <= 375 ? 4 : 12,
    flexDirection: 'row',
  },
  vaultContentWrapper: {
    flex: 1,
  },
  vaultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 0,
  },
  vaultHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  vaultIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    position: 'relative',
    alignSelf: 'center',
  },
  vaultStatusIndicator: {
    position: 'absolute',
    top: -1,
    right: -1,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#59AA8A',
  },
  vaultInfo: {
    flex: 1,
  },
  vaultTitle: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  vaultHealth: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
  },
  vaultDetailsContainer: {
    marginLeft: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  vaultDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  vaultValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vaultOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createVaultButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  createVaultButtonText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: '#FFFFFF',
    fontWeight: '600',
  },
  vaultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  vaultLabel: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  vaultValue: {
    fontSize: 14,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    marginLeft: 4,
  },
  vaultValueWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vaultProgressBar: {
    flexDirection: 'row',
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
    marginVertical: 16,
  },
  vaultProgressFill: {
    backgroundColor: '#59AA8A',
    height: '100%',
  },
  vaultProgressLocked: {
    backgroundColor: '#59AA8A',
    opacity: 0.3,
    height: '100%',
  },
  vaultFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  vaultFooterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  vaultDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#59AA8A',
  },
  vaultDotLocked: {
    opacity: 0.3,
  },
  vaultFooterValue: {
    fontSize: 14,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    marginLeft: 4,
  },
  vaultFooterLabel: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  assetCardPlaceholder: {
    opacity: 0,
    height: 72,
  },
  assetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  assetLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  btcIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    overflow: 'hidden',
  },
  ducatIcon: {
    borderRadius: 20,
  },
  logoImage: {
    width: 40,
    height: 40,
  },
  assetInfo: {
    flex: 1,
  },
  assetName: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    marginBottom: 0,
  },
  vaultAssetName: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    paddingTop: 4,
    marginBottom: 0,
  },
  assetAmount: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  assetAmountIcon: {
    width: 12,
    height: 12,
    marginRight: 0,
  },
  assetSubtext: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
  },
  assetValue: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  addressSection: {
    marginTop: 20,
    marginBottom: 20,
  },
  addressLabel: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 8,
  },
  addressContainer: {
    minHeight: 36,
  },
  addressText: {
    fontSize: 12,
    color: COLORS.VERY_LIGHT_GRAY,
    fontFamily: 'monospace',
    marginBottom: 4,
  },
  copyHint: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.PRIMARY_BLUE,
    fontStyle: 'italic',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 16,
    padding: 24,
    width: '80%',
    maxWidth: 300,
    overflow: 'hidden',
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 12,
  },
  accountInput: {
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    color: COLORS.DARK_GRAY,
    padding: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
  },
  modalButton: {
    flex: 1,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginRight: 16,
  },
  modalButtonConfirm: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  modalButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
  },
  actionsRow: {
    flexDirection: 'row',
    marginTop: 24,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  sendButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    marginRight: 16,
  },
  receiveButton: {
    backgroundColor: COLORS.TEAL,
  },
  actionButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
  },
  seedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SCREEN_WIDTH <= 375 ? 6 : 8,
  },
  seedBox: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: SCREEN_WIDTH <= 375 ? 12 : 16,
    borderRadius: 8,
    marginBottom: SCREEN_WIDTH <= 375 ? 8 : 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seedNumber: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginRight: 8,
    minWidth: 20,
  },
  seedWord: {
    fontSize: SCREEN_WIDTH <= 375 ? 14 : 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  verifyBox: {
    marginBottom: 8,
  },
  verifyLabel: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  choicesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  choiceButton: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: 8,
    borderRadius: 8,
    marginBottom: 4,
    borderWidth: 2,
    borderColor: COLORS.BORDER_COLOR,
  },
  choiceButtonSelected: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  choiceText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'center',
    fontWeight: '600',
  },
  choiceTextSelected: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  addressTypeSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  addressTypeButton: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.BORDER_COLOR,
    alignItems: 'center',
  },
  addressTypeButtonSelected: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  addressTypeText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  addressTypeTextSelected: {
    color: COLORS.VERY_LIGHT_GRAY,
  },
  addressTypeSubtext: {
    color: COLORS.SECONDARY_TEXT,
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  warning: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.DANGER_RED,
    marginTop: 16,
    textAlign: 'center',
    fontWeight: 'bold',
    lineHeight: 18,
  },
  runesContainer: {
    backgroundColor: COLORS.CARD_BG,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: COLORS.TEAL,
  },
  runesLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.TEAL,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  runeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.PRIMARY_BLUE,
  },
  runeName: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    flex: 1,
  },
  runeAmount: {
    fontSize: 16,
    color: COLORS.TEAL,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  seedInput: {
    backgroundColor: COLORS.CARD_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    marginBottom: 16,
    textAlignVertical: 'top',
    minHeight: 100,
  },
  seedWordsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    marginBottom: 16,
    width: '100%',
  },
  seedWordContainer: {
    width: '47%',
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seedWordNumber: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    width: 20,
    textAlign: 'right',
    marginRight: 8,
  },
  seedWordInput: {
    flex: 1,
    backgroundColor: COLORS.CARD_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  label: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  switchingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
    borderRadius: 16,
  },
  switchingText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    marginTop: 12,
  },
  balanceWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  balanceIcon: {
    width: 24,
    height: 24,
    marginRight: 4,
  },
  assetValueWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  assetIcon: {
    width: 16,
    height: 16,
    marginRight: 3,
  },
  walletContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 0,
    paddingTop: 0,
    backgroundColor: COLORS.DARK_BG,
  },
  // Mutinynet banner - Full Width
  mutinynetBanner: {
    backgroundColor: COLORS.CARD_BG,
    paddingVertical: 8,
    paddingHorizontal: 0,
    width: '100%',
    alignSelf: 'stretch',
    borderRadius: 0,
    marginTop: STATUS_BAR_HEIGHT + 10,
    marginBottom: HORIZONTAL_PADDING,
    marginLeft: 0,
    marginRight: 0,
    alignItems: 'center',
  },
  mutinynetBannerText: {
    color: COLORS.PURPLE,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
    fontFamily: 'CabinetGrotesk-Medium',
  },
  priceChipsContainer: {
    flexDirection: 'row',
    marginBottom: 0,
    width: '100%',
  },
  priceChip: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceChipBTC: {
    flex: 2,
    marginRight: 8,
  },
  priceChipUnit: {
    flex: 1,
  },
  priceChipIcon: {
    width: 24,
    height: 24,
    marginRight: 8,
  },
  priceChipName: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '500',
    marginRight: 8,
  },
  priceChipValue: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  // Xverse-style header
  xverseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  xverseHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  copyButton: {
    padding: 4,
  },
  accountIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.PRIMARY_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  accountIconText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  xverseAccountName: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  copyIconButton: {
    padding: 4,
  },
  copyIcon: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  xverseHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerIconButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIcon: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  headerIconImage: {
    width: 24,
    height: 24,
    tintColor: COLORS.VERY_LIGHT_GRAY,
  },
  // Xverse-style balance section
  xverseBalanceSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  xverseBalanceLeft: {
    flex: 1,
  },
  xverseBalanceLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 4,
  },
  xverseBalanceAmount: {
    fontSize: SCREEN_WIDTH <= 375 ? 36 : 44,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  // Removed duplicates - using balanceWithIcon and balanceIcon at lines 909-918
  balanceDivider: {
    height: 0,
    backgroundColor: COLORS.CARD_BG,
    marginHorizontal: 0,
    marginBottom: 8,
  },
  portfolioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.CARD_BG,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    gap: 8,
  },
  portfolioIcon: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  portfolioText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '500',
  },
  // Xverse-style action buttons
  xverseActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginBottom: 8,
    gap: 16,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  xverseActionButton: {
    flex: 1,
    height: 56,
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  xverseActionIcon: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    justifyContent: 'center',
    alignItems: 'center',
  },
  xverseActionIconText: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.BLACK,
    fontWeight: '600',
  },
  xverseActionIconImage: {
    width: 20,
    height: 20,
    tintColor: COLORS.BLACK,
  },
  xverseActionLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.BLACK,
    fontWeight: '600',
  },
  lockedContainer: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: HORIZONTAL_PADDING,
    paddingTop: HORIZONTAL_PADDING,
  },
  lockIconContainer: {
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 40,
  },
  lockIcon: {
    fontSize: 80,
    fontFamily: 'CabinetGrotesk-Regular',
    marginBottom: 20,
  },
  lockedText: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 12,
  },
  lockedSubtext: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    textAlign: 'center',
  },
  unlockButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
  },
  unlockButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  pinButton: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginTop: 16,
  },
  pinContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  pinTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 12,
  },
  pinSubtext: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 20,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  pinError: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.DANGER_RED,
    marginBottom: 20,
    textAlign: 'center',
  },
  pinDotsContainer: {
    flexDirection: 'row',
    marginBottom: 50,
  },
  pinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.BORDER_COLOR,
    marginHorizontal: 8,
  },
  pinDotFilled: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  pinKeypad: {
    width: '100%',
    maxWidth: 300,
  },
  pinRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  pinKey: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.DARK_BG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pinKeyText: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  pinCancelButton: {
    marginTop: 20,
    paddingVertical: 16,
    alignItems: 'center',
  },
  pinCancelText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
    textAlign: 'center',
  },
  settingsButton: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.MEDIUM_GRAY,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  settingsIcon: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  settingsModal: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    padding: 0,
    width: '85%',
    maxWidth: 400,
  },
  settingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SCREEN_WIDTH <= 375 ? 8 : 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER_COLOR,
  },
  settingsTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
  },
  closeButton: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '300',
  },
  settingsOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: SCREEN_WIDTH <= 375 ? 8 : 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER_COLOR,
  },
  settingsOptionIcon: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Regular',
    marginRight: SCREEN_WIDTH <= 375 ? 8 : 16,
    width: 32,
  },
  settingsOptionText: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
  },
  settingsOptionArrow: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.LIGHT_GRAY,
  },
  settingsToggle: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.SECONDARY_TEXT,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: COLORS.DARK_GRAY,
  },
  settingsToggleOn: {
    color: COLORS.VERY_LIGHT_GRAY,
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  settingsDivider: {
    height: 8,
    backgroundColor: COLORS.OFF_WHITE,
  },
  dangerOption: {
    borderBottomWidth: 0,
  },
  dangerText: {
    color: COLORS.DANGER_RED,
  },
  seedPhraseTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    textAlign: 'center',
    marginBottom: 20,
  },
  seedPhraseWarning: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.DANGER_RED,
    backgroundColor: COLORS.PINK_WHITE,
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    textAlign: 'center',
    lineHeight: 18,
  },
  // Intent UI styles
  intentModal: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    padding: 0,
    width: '90%',
    maxWidth: 420,
    maxHeight: '80%',
  },
  intentContent: {
    padding: 20,
  },
  intentInput: {
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    color: COLORS.DARK_GRAY,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    marginBottom: 20,
  },
  reviewSection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER_COLOR,
  },
  reviewSectionTotal: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.PRIMARY_BLUE,
    paddingTop: 12,
  },
  reviewLabel: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 4,
  },
  reviewLabelTotal: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  reviewValue: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    marginBottom: 3,
  },
  reviewValueTotal: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
  },
  reviewSubtext: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
  },
  reviewAddressSmall: {
    fontSize: 12,
    color: COLORS.SECONDARY_TEXT,
    fontFamily: 'monospace',
    marginTop: 3,
  },
  // Bottom sheet styles
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bottomSheetBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.DARK_BG,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 40,
    paddingHorizontal: 20,
    paddingTop: 16,
    minHeight: '50%',
    maxHeight: '90%',
    zIndex: 1000,
  },
  bottomSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: COLORS.MEDIUM_GRAY,
    borderRadius: 4,
    alignSelf: 'center',
    marginBottom: 20,
  },
  bottomSheetTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 25,
    textAlign: 'center',
  },
  assetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.DARK_BG,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderRadius: 12,
    marginBottom: 12,
  },
  assetOptionLogo: {
    width: 44,
    height: 44,
    marginRight: 16,
    borderRadius: 22,
  },
  assetOptionInfo: {
    flex: 1,
  },
  assetOptionTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 3,
  },
  assetOptionSubtitle: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
  },
  assetOptionArrow: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  assetOptionValue: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  // Disabled asset option styles
  assetOptionDisabled: {
    opacity: 0.4,
  },
  assetOptionTitleDisabled: {
    color: COLORS.SECONDARY_TEXT,
  },
  assetOptionSubtitleDisabled: {
    color: COLORS.SECONDARY_TEXT,
  },
  assetOptionValueDisabled: {
    color: COLORS.SECONDARY_TEXT,
  },
  // Amount input bottom sheet styles
  bottomSheetBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  bottomSheetBackArrow: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.PRIMARY_BLUE,
    marginRight: 4,
  },
  bottomSheetBackText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.PRIMARY_BLUE,
  },
  amountInputContainer: {
    alignItems: 'flex-start',
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 0,
    width: '100%',
    flex: 1,
    justifyContent: 'space-between',
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  amountAssetSymbol: {
    width: 36,
    height: 36,
    marginRight: 12,
  },
  amountInput: {
    fontSize: 48,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    minWidth: 100,
  },
  amountInputLabel: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 40,
  },
  amountContinueButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 16,
    paddingHorizontal: 60,
    borderRadius: 12,
    width: '100%',
  },
  amountContinueButtonDisabled: {
    backgroundColor: COLORS.DARK_GRAY,
  },
  amountContinueButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    textAlign: 'center',
  },
  // Balance footer at bottom of send sheets
  sendBalanceFooter: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    flexDirection: 'column',
    gap: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER_COLOR,
  },
  sendBalanceFooterRow: {
    flexDirection: 'column',
  },
  sendBalanceFooterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  sendBalanceFooterLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  sendBalanceFooterAmount: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  sendBalanceFooterUsd: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  // Address input styles
  addressInputTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 20,
    textAlign: 'center',
  },
  addressInputTitleLeft: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 4,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  addressInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    gap: 12,
    width: '100%',
  },
  addressInput: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.BORDER_COLOR,
    textAlign: 'left',
  },
  pasteButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pasteButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
  },
  addressError: {
    color: COLORS.DANGER_RED,
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
    marginBottom: 4,
  },
  addressContinueButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 0,
    width: '100%',
  },
  addressContinueButtonDisabled: {
    backgroundColor: COLORS.DARK_GRAY,
    opacity: 0.5,
  },
  // Send To Header
  sendToHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    marginBottom: 12,
  },
  sendToLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sendToLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  sendToAddress: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '500',
  },
  addressTypeTag: {
    backgroundColor: COLORS.DARK_GRAY,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  // Removed duplicate - using addressTypeText at line 776
  // Amount Balance Row
  amountBalanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 12,
  },
  amountBalanceLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  maxButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  maxButtonText: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: '600',
  },
  // Amount Input Large
  amountInputLarge: {
    fontSize: 56,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    flex: 1,
  },
  amountAssetSymbolRight: {
    width: 32,
    height: 32,
    marginLeft: 8,
    marginBottom: 8,
  },
  amountUsdValue: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginTop: 8,
    marginBottom: 40,
  },
  // Review bottom sheet styles
  reviewTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 32,
    textAlign: 'center',
  },
  // Removed duplicates - using reviewLabel and reviewValue at lines 1418-1434
  reviewAmountLarge: {
    fontSize: 44,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    textAlign: 'center',
    marginBottom: 4,
  },
  reviewAmountSats: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    textAlign: 'center',
    marginBottom: 12,
  },
  reviewTotal: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.PRIMARY_BLUE,
    textAlign: 'center',
    marginBottom: 32,
  },
  // Success screen styles
  successCloseButton: {
    position: 'absolute',
    top: 16,
    right: 20,
    zIndex: 10,
    padding: 12,
  },
  successCloseText: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '300',
  },
  successCheckmarkContainer: {
    marginBottom: 20,
    marginTop: 12,
  },
  successCheckmark: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'transparent',
    borderWidth: 3,
    borderColor: COLORS.LIGHT_GREEN,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successCheckmarkText: {
    fontSize: 40,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.LIGHT_GREEN,
    fontWeight: 'bold',
  },
  successTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 32,
    textAlign: 'center',
  },
  successTxid: {
    fontSize: 12,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    textAlign: 'center',
    marginBottom: 20,
  },

  // Lock Screen Styles
  lockScreen: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  lockIconArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  lockPasswordIcon: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockPasswordText: {
    fontSize: 32,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    letterSpacing: 8,
    marginBottom: 8,
  },
  lockPadlock: {
    fontSize: 40,
    fontFamily: 'CabinetGrotesk-Bold',
    position: 'absolute',
    right: -25,
    top: -5,
  },
  lockTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 32,
    marginTop: 20,
    textAlign: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  faceIdButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 20,
    marginHorizontal: HORIZONTAL_PADDING,
  },
  faceIdText: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: '500',
    marginRight: 8,
  },
  faceIdArrow: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
  },
  lockPinError: {
    color: COLORS.BRIGHT_RED,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    marginBottom: 20,
    textAlign: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  lockPinDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 50,
    gap: 16,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  lockPinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.MEDIUM_GRAY,
  },
  lockPinDotFilled: {
    backgroundColor: COLORS.WHITE,
  },
  lockKeypad: {
    width: '100%',
    maxWidth: 352,
    marginBottom: 40,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  lockKeypadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 32,
  },
  lockKey: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  lockKeyText: {
    fontSize: 32,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  lockKeyIcon: {
    width: 24,
    height: 24,
    tintColor: COLORS.WHITE,
  },
  lockKeyCancelText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  lockKeyDelete: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  // Biometric Prompt styles
  biometricPromptModal: {
    backgroundColor: COLORS.VERY_DARK_GRAY,
    borderRadius: 20,
    padding: 32,
    width: '85%',
    maxWidth: 400,
  },
  biometricPromptTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 16,
    textAlign: 'center',
  },
  biometricPromptText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 24,
  },
  biometricPromptButtons: {
    gap: 12,
  },
  biometricPromptButton: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  biometricPromptButtonYes: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  biometricPromptButtonNo: {
    backgroundColor: COLORS.OFF_WHITE,
  },
  biometricPromptButtonText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
  },
  biometricPromptButtonTextNo: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.DARK_GRAY,
  },
  // Confirmation Modal styles
  confirmationModal: {
    backgroundColor: COLORS.VERY_DARK_GRAY,
    borderRadius: 20,
    padding: 32,
    width: '85%',
    maxWidth: 400,
  },
  confirmationModalIconContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  confirmationModalTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 16,
    textAlign: 'center',
  },
  confirmationModalText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 22,
  },
  confirmationModalButtons: {
    gap: 12,
  },
  confirmationModalButton: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmationModalButtonPrimary: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  confirmationModalButtonDestructive: {
    backgroundColor: COLORS.DANGER_RED,
  },
  confirmationModalButtonCancel: {
    backgroundColor: COLORS.OFF_WHITE,
  },
  confirmationModalButtonText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
  },
  confirmationModalButtonTextCancel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.DARK_GRAY,
  },
  // Receive address styles
  receiveAddressRow: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  receiveAddressInfo: {
    flex: 1,
    marginRight: 16,
  },
  receiveAddressLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  receiveAddressLabel: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  receiveAddress: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  receiveAddressTag: {
    backgroundColor: COLORS.CARD_BG,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  receiveAddressTagText: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
  },
  receiveQrButton: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  receiveQrIcon: {
    width: 24,
    height: 24,
    tintColor: COLORS.VERY_LIGHT_GRAY,
  },
  // QR Modal styles
  qrModalContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.DARK_BG,
    zIndex: 99999,
  },
  qrModalNetworkBar: {
    backgroundColor: COLORS.CARD_BG,
    paddingVertical: SCREEN_WIDTH < 375 ? 4 : 6,
    paddingHorizontal: 0,
    width: '100%',
    alignSelf: 'stretch',
    borderRadius: 0,
    marginTop: SCREEN_WIDTH < 375 ? 20 : STATUS_BAR_HEIGHT,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrModalNetworkText: {
    color: COLORS.PURPLE,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
    fontFamily: 'CabinetGrotesk-Medium',
  },
  qrModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: SCREEN_WIDTH < 375 ? 8 : 16,
    paddingBottom: SCREEN_WIDTH < 375 ? 8 : 16,
  },
  qrModalBackButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  qrModalBackArrow: {
    fontSize: 36,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  qrModalBackIcon: {
    width: 24,
    height: 24,
    tintColor: COLORS.VERY_LIGHT_GRAY,
  },
  qrModalMenuButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  qrModalMenuIcon: {
    fontSize: 24,
    color: COLORS.VERY_LIGHT_GRAY,
  },
  qrModalContent: {
    alignItems: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: SCREEN_WIDTH <= 400 ? 10 : 20,
    paddingBottom: SCREEN_WIDTH <= 400 ? 24 : 32,
    flexGrow: 1,
  },
  qrModalTitle: {
    fontSize: SCREEN_WIDTH < 375 ? 20 : 28,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: SCREEN_WIDTH < 375 ? 4 : 8,
    textAlign: 'center',
  },
  qrModalSubtitle: {
    fontSize: SCREEN_WIDTH < 375 ? 12 : 15,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: SCREEN_WIDTH <= 400 ? 8 : 40,
    textAlign: 'center',
  },
  qrCodeContainer: {
    backgroundColor: COLORS.WHITE,
    padding: SCREEN_WIDTH < 375 ? 10 : 20,
    borderRadius: 16,
    marginBottom: SCREEN_WIDTH < 375 ? 12 : 32,
  },
  qrAddressContainer: {
    width: '100%',
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 12,
    padding: SCREEN_WIDTH < 375 ? 12 : 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SCREEN_WIDTH < 375 ? 12 : 16,
  },
  qrAddressLeft: {
    flex: 1,
    marginRight: 12,
  },
  qrAddressLabelText: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
    marginBottom: 8,
  },
  qrAddressFullText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    lineHeight: 20,
  },
  qrCopyButton: {
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
  },
  qrCopyButtonText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.DARK_BG,
    fontWeight: '600',
  },
  qrShareButton: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.BORDER_COLOR,
    paddingVertical: SCREEN_WIDTH < 375 ? 12 : 14,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  qrShareIcon: {
    fontSize: 20,
    color: COLORS.VERY_LIGHT_GRAY,
  },
  qrShareButtonText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  // Toast notification styles
  toastContainer: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 999999,
  },
  toastContainerError: {
    backgroundColor: COLORS.DANGER_RED,
  },
  toastText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.BLACK,
    fontWeight: '600',
    textAlign: 'center',
  },
  // Transaction History styles
  historySheet: {
    maxHeight: '70%',
    paddingBottom: 20,
  },
  historyHandleArea: {
    paddingTop: 12,
    paddingBottom: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
    width: '100%',
  },
  historyScrollView: {
    flex: 1,
    width: '100%',
  },
  historyLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  historyLoadingText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
    marginTop: 16,
  },
  historyEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  historyEmptyText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  historyTxRow: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER_COLOR,
  },
  historyLogoImage: {
    width: 40,
    height: 40,
  },
  historyTxTopRow: {
    flexDirection: 'row',
    marginBottom: 4,
    alignItems: 'center',
  },
  historyTxBottomRow: {
    flexDirection: 'row',
  },
  historyTxColumn1: {
    flex: 1,
  },
  historyTxRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 3,
    justifyContent: 'space-between',
  },
  historyTxColumn2: {},
  historyTxColumn3: {
    alignItems: 'flex-end',
  },
  historyTxAmount: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    marginBottom: 4,
  },
  historyTxAmountSent: {
    color: COLORS.DANGER_RED,
  },
  historyTxAmountReceived: {
    color: COLORS.TEAL,
  },
  historyTxAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  vaultAmountChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 4,
    minWidth: 85,
    justifyContent: 'center',
  },
  vaultAmountChipIcon: {
    marginRight: 8,
  },
  vaultAmountChipText: {
    fontSize: 14,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: '600',
  },
  historyTxDate: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.SECONDARY_TEXT,
  },
  historyTxRight: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    minWidth: 120,
  },
});
export default styles;
