import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './utils/colors';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: COLORS.BLACK,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  splashContainer: {
    flex: 1,
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogo: {
    width: 150,
    height: 150,
    marginBottom: 20,
  },
  splashTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 5,
    letterSpacing: 2,
  },
  splashSubtitle: {
    fontSize: 14,
    fontWeight: '300',
    color: COLORS.PURPLE,
    letterSpacing: 1,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 0,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 2,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '300',
    color: COLORS.PURPLE,
    marginBottom: 30,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  welcomeContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
  },
  welcomeContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  welcomeButtons: {
    width: '100%',
    paddingBottom: 20,
  },
  welcomeLogo: {
    width: 120,
    height: 120,
  },
  welcomeTitle: {
    fontSize: 24,
    color: COLORS.WHITE,
    marginBottom: 8,
    textAlign: 'center',
    fontWeight: 'bold',
    paddingHorizontal: 10,
  },
  welcomeTagline: {
    fontSize: 16,
    color: COLORS.WHITE,
    marginBottom: 30,
    textAlign: 'center',
    fontWeight: '400',
    paddingHorizontal: 10,
  },
  topAddAccountButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.PRIMARY_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 16,
    borderRadius: 10,
    marginTop: 15,
    width: '100%',
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  resetButton: {
    backgroundColor: COLORS.DANGER_RED,
    marginTop: 30,
  },
  secondaryButton: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginTop: 15,
  },
  walletInfo: {
    width: '100%',
    backgroundColor: COLORS.DARK_BG,
    padding: 20,
    borderRadius: 15,
    marginTop: 4,
  },
  stepIndicator: {
    fontSize: 16,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  introTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 20,
    textAlign: 'center',
  },
  introText: {
    fontSize: 16,
    color: COLORS.MEDIUM_GRAY,
    lineHeight: 24,
    marginBottom: 25,
    textAlign: 'center',
  },
  infoBox: {
    backgroundColor: COLORS.OFF_WHITE,
    borderRadius: 12,
    padding: 20,
    marginBottom: 25,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.PRIMARY_BLUE,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 12,
  },
  infoText: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
    lineHeight: 22,
  },
  warningText: {
    fontSize: 14,
    color: COLORS.DANGER_RED,
    backgroundColor: COLORS.PINK_WHITE,
    padding: 15,
    borderRadius: 8,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  walletTitle: {
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    flex: 1,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addAccountButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.PRIMARY_BLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addAccountText: {
    fontSize: 20,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  addressToggle: {
    flexDirection: 'row',
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 8,
    overflow: 'hidden',
  },
  toggleButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  toggleButtonLeft: {
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  toggleButtonRight: {
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  toggleButtonActive: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  toggleText: {
    fontSize: 12,
    color: COLORS.MEDIUM_GRAY,
    fontWeight: '600',
  },
  toggleTextActive: {
    color: COLORS.VERY_LIGHT_GRAY,
  },
  totalBalanceSection: {
    marginBottom: 30,
  },
  totalBalanceLabel: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
    marginBottom: 8,
  },
  balanceContainer: {
    minHeight: 43,
    justifyContent: 'center',
  },
  loadingContainer: {
    height: 43,
    justifyContent: 'center',
  },
  totalBalanceAmount: {
    fontSize: 36,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  totalBalanceAmountSmall: {
    fontSize: 28,
  },
  assetsContainer: {
    minHeight: 144,
  },
  assetCard: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    height: 72,
  },
  assetCardPlaceholder: {
    opacity: 0,
    height: 72,
  },
  assetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  assetLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  btcIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  ducatIcon: {
    // Unit icon styling (if needed)
  },
  logoImage: {
    width: 40,
    height: 40,
  },
  assetName: {
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    marginBottom: 4,
  },
  assetSubtext: {
    fontSize: 12,
    color: COLORS.MEDIUM_GRAY,
  },
  assetValue: {
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  addressSection: {
    marginTop: 20,
    marginBottom: 20,
  },
  addressLabel: {
    fontSize: 12,
    color: COLORS.MEDIUM_GRAY,
    marginBottom: 8,
  },
  addressContainer: {
    minHeight: 36,
  },
  addressText: {
    fontSize: 12,
    color: COLORS.VERY_LIGHT_GRAY,
    fontFamily: 'monospace',
    marginBottom: 4,
  },
  copyHint: {
    fontSize: 10,
    color: COLORS.PRIMARY_BLUE,
    fontStyle: 'italic',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 15,
    padding: 24,
    width: '80%',
    maxWidth: 300,
    overflow: 'hidden',
  },
  modalTitle: {
    fontSize: 18,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalLabel: {
    fontSize: 14,
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 8,
  },
  accountInput: {
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    color: COLORS.DARK_GRAY,
    padding: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginRight: 12,
  },
  modalButtonConfirm: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  modalButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 14,
    fontWeight: '600',
  },
  actionsRow: {
    flexDirection: 'row',
    marginTop: 24,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  sendButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    marginRight: 12,
  },
  receiveButton: {
    backgroundColor: COLORS.TEAL,
  },
  actionButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 14,
    fontWeight: '600',
  },
  seedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  seedBox: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seedNumber: {
    fontSize: 12,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginRight: 8,
    minWidth: 20,
  },
  seedWord: {
    fontSize: 14,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  verifyBox: {
    marginBottom: 20,
  },
  verifyLabel: {
    fontSize: 16,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  choicesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  choiceButton: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: COLORS.CARD_BG,
  },
  choiceButtonSelected: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  choiceText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '600',
  },
  choiceTextSelected: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  addressTypeSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  addressTypeButton: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: COLORS.CARD_BG,
    alignItems: 'center',
  },
  addressTypeButtonSelected: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  addressTypeText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  addressTypeTextSelected: {
    color: COLORS.VERY_LIGHT_GRAY,
  },
  addressTypeSubtext: {
    color: COLORS.MEDIUM_GRAY,
    fontSize: 11,
  },
  warning: {
    fontSize: 12,
    color: COLORS.DANGER_RED,
    marginTop: 15,
    textAlign: 'center',
    fontWeight: 'bold',
    lineHeight: 18,
  },
  runesContainer: {
    backgroundColor: COLORS.CARD_BG,
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: COLORS.TEAL,
  },
  runesLabel: {
    fontSize: 14,
    color: COLORS.TEAL,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  runeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.PRIMARY_BLUE,
  },
  runeName: {
    fontSize: 12,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    flex: 1,
  },
  runeAmount: {
    fontSize: 16,
    color: COLORS.TEAL,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  seedInput: {
    backgroundColor: COLORS.CARD_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 14,
    marginBottom: 15,
    textAlignVertical: 'top',
    minHeight: 100,
  },
  seedWordsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  seedWordContainer: {
    width: '48%',
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seedWordNumber: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 12,
    fontWeight: 'bold',
    width: 25,
    textAlign: 'right',
    marginRight: 8,
  },
  seedWordInput: {
    flex: 1,
    backgroundColor: COLORS.CARD_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 14,
  },
  label: {
    fontSize: 14,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  switchingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
    borderRadius: 15,
  },
  switchingText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
  },
  balanceWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  balanceIcon: {
    width: 24,
    height: 24,
    marginRight: 4,
  },
  assetValueWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  assetIcon: {
    width: 14,
    height: 14,
    marginRight: 3,
  },
  walletContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 20,
  },
  priceChipsContainer: {
    flexDirection: 'row',
    marginBottom: 0,
    width: '100%',
  },
  priceChip: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceChipBTC: {
    flex: 2,
    marginRight: 8,
  },
  priceChipUnit: {
    flex: 1,
  },
  priceChipIcon: {
    width: 24,
    height: 24,
    marginRight: 6,
  },
  priceChipName: {
    fontSize: 13,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '500',
    marginRight: 8,
  },
  priceChipValue: {
    fontSize: 14,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
  },
  lockedContainer: {
    flex: 1,
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  lockIconContainer: {
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 40,
  },
  lockIcon: {
    fontSize: 80,
    marginBottom: 20,
  },
  lockedText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 10,
  },
  lockedSubtext: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
    textAlign: 'center',
  },
  unlockButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 10,
  },
  unlockButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  pinButton: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginTop: 15,
  },
  pinContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  pinTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 10,
  },
  pinSubtext: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
    marginBottom: 20,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  pinError: {
    fontSize: 14,
    color: COLORS.DANGER_RED,
    marginBottom: 20,
    textAlign: 'center',
  },
  pinDotsContainer: {
    flexDirection: 'row',
    marginBottom: 50,
  },
  pinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.VERY_LIGHT_GRAY,
    marginHorizontal: 8,
  },
  pinDotFilled: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  pinKeypad: {
    width: '100%',
    maxWidth: 300,
  },
  pinRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  pinKey: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    backgroundColor: COLORS.DARK_BG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pinKeyText: {
    fontSize: 28,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  pinCancelButton: {
    marginTop: 20,
    paddingVertical: 15,
  },
  pinCancelText: {
    fontSize: 16,
    color: COLORS.MEDIUM_GRAY,
    fontWeight: '600',
  },
  settingsButton: {
    position: 'absolute',
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.MEDIUM_GRAY,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  settingsIcon: {
    fontSize: 20,
  },
  settingsModal: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    padding: 0,
    width: '85%',
    maxWidth: 400,
  },
  settingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.OFF_WHITE_GRAY,
  },
  settingsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
  },
  closeButton: {
    fontSize: 24,
    color: COLORS.MEDIUM_GRAY,
    fontWeight: '300',
  },
  settingsOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.OFF_WHITE,
  },
  settingsOptionIcon: {
    fontSize: 22,
    marginRight: 15,
    width: 30,
  },
  settingsOptionText: {
    flex: 1,
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
  },
  settingsOptionArrow: {
    fontSize: 20,
    color: COLORS.LIGHT_GRAY,
  },
  settingsToggle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.MEDIUM_GRAY,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: COLORS.DARK_GRAY,
  },
  settingsToggleOn: {
    color: COLORS.WHITE,
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  settingsDivider: {
    height: 8,
    backgroundColor: COLORS.OFF_WHITE,
  },
  dangerOption: {
    borderBottomWidth: 0,
  },
  dangerText: {
    color: COLORS.DANGER_RED,
  },
  seedPhraseTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    textAlign: 'center',
    marginBottom: 20,
  },
  seedPhraseWarning: {
    fontSize: 14,
    color: COLORS.DANGER_RED,
    backgroundColor: COLORS.PINK_WHITE,
    padding: 15,
    borderRadius: 8,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 20,
  },
  // Intent UI styles
  intentModal: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    padding: 0,
    width: '90%',
    maxWidth: 420,
    maxHeight: '80%',
  },
  intentContent: {
    padding: 20,
  },
  intentInput: {
    backgroundColor: COLORS.VERY_LIGHT_GRAY,
    color: COLORS.DARK_GRAY,
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 14,
    marginBottom: 20,
  },
  reviewSection: {
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.DARK_GRAY,
  },
  reviewSectionTotal: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.PRIMARY_BLUE,
    paddingTop: 10,
  },
  reviewLabel: {
    fontSize: 13,
    color: COLORS.MEDIUM_GRAY,
    marginBottom: 5,
  },
  reviewLabelTotal: {
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  reviewValue: {
    fontSize: 18,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
    marginBottom: 3,
  },
  reviewValueTotal: {
    fontSize: 22,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
  },
  reviewSubtext: {
    fontSize: 12,
    color: COLORS.MEDIUM_GRAY,
  },
  reviewAddressSmall: {
    fontSize: 11,
    color: COLORS.MEDIUM_GRAY,
    fontFamily: 'monospace',
    marginTop: 3,
  },
  // Bottom sheet styles
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bottomSheetBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.DARK_BG,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 40,
    paddingHorizontal: 20,
    paddingTop: 15,
    minHeight: '50%',
    zIndex: 1000,
  },
  bottomSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: COLORS.MEDIUM_GRAY,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  bottomSheetTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 25,
    textAlign: 'center',
  },
  assetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.DARK_BG,
    padding: 18,
    borderRadius: 12,
    marginBottom: 12,
  },
  assetOptionLogo: {
    width: 50,
    height: 50,
    marginRight: 15,
  },
  assetOptionInfo: {
    flex: 1,
  },
  assetOptionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 3,
  },
  assetOptionSubtitle: {
    fontSize: 13,
    color: COLORS.MEDIUM_GRAY,
  },
  assetOptionArrow: {
    fontSize: 24,
    color: COLORS.MEDIUM_GRAY,
  },
  // Amount input bottom sheet styles
  bottomSheetBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  bottomSheetBackArrow: {
    fontSize: 24,
    color: COLORS.PRIMARY_BLUE,
    marginRight: 5,
  },
  bottomSheetBackText: {
    fontSize: 16,
    color: COLORS.PRIMARY_BLUE,
  },
  amountInputContainer: {
    alignItems: 'flex-start',
    paddingTop: 20,
    paddingHorizontal: 15,
    paddingBottom: 0,
    width: '100%',
    flex: 1,
    justifyContent: 'space-between',
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  amountAssetSymbol: {
    width: 35,
    height: 35,
    marginRight: 12,
  },
  amountInput: {
    fontSize: 48,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    minWidth: 100,
  },
  amountInputLabel: {
    fontSize: 18,
    color: COLORS.MEDIUM_GRAY,
    marginBottom: 40,
  },
  amountContinueButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 16,
    paddingHorizontal: 60,
    borderRadius: 12,
    width: '100%',
  },
  amountContinueButtonDisabled: {
    backgroundColor: COLORS.DARK_GRAY,
  },
  amountContinueButtonText: {
    color: COLORS.WHITE,
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  // Address input styles
  addressInputTitle: {
    fontSize: 18,
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 20,
    textAlign: 'center',
  },
  addressInputTitleLeft: {
    fontSize: 14,
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 4,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  addressInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    gap: 12,
    width: '100%',
  },
  addressInput: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 12,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.DARK_GRAY,
    textAlign: 'left',
  },
  pasteButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pasteButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 14,
    fontWeight: '600',
  },
  addressError: {
    color: '#ff4444',
    fontSize: 12,
    textAlign: 'left',
    marginBottom: 4,
  },
  addressContinueButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 0,
    width: '100%',
  },
  addressContinueButtonDisabled: {
    backgroundColor: COLORS.DARK_GRAY,
    opacity: 0.5,
  },
  // Send To Header
  sendToHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    marginBottom: 20,
  },
  sendToLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sendToLabel: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
  },
  sendToAddress: {
    fontSize: 14,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '500',
  },
  addressTypeTag: {
    backgroundColor: COLORS.DARK_GRAY,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 6,
  },
  addressTypeText: {
    fontSize: 12,
    color: COLORS.MEDIUM_GRAY,
  },
  // Amount Balance Row
  amountBalanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  amountBalanceLabel: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
  },
  maxButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_BLUE,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  maxButtonText: {
    fontSize: 12,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: '600',
  },
  // Amount Input Large
  amountInputLarge: {
    fontSize: 56,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    flex: 1,
  },
  amountAssetSymbolRight: {
    width: 40,
    height: 40,
    marginLeft: 12,
  },
  amountUsdValue: {
    fontSize: 18,
    color: COLORS.MEDIUM_GRAY,
    marginTop: 8,
    marginBottom: 40,
  },
  // Review bottom sheet styles
  reviewTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 30,
    textAlign: 'center',
  },
  reviewLabel: {
    fontSize: 13,
    color: COLORS.LIGHT_MEDIUM_GRAY,
    marginTop: 20,
    marginBottom: 6,
    textAlign: 'center',
  },
  reviewValue: {
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 10,
  },
  reviewAmountLarge: {
    fontSize: 42,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    textAlign: 'center',
    marginBottom: 4,
  },
  reviewAmountSats: {
    fontSize: 14,
    color: COLORS.MEDIUM_GRAY,
    textAlign: 'center',
    marginBottom: 10,
  },
  reviewTotal: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.PRIMARY_BLUE,
    textAlign: 'center',
    marginBottom: 30,
  },
  // Success screen styles
  successCloseButton: {
    position: 'absolute',
    top: 15,
    right: 20,
    zIndex: 10,
    padding: 10,
  },
  successCloseText: {
    fontSize: 28,
    color: COLORS.MEDIUM_GRAY,
    fontWeight: '300',
  },
  successCheckmarkContainer: {
    marginBottom: 20,
    marginTop: 10,
  },
  successCheckmark: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'transparent',
    borderWidth: 3,
    borderColor: COLORS.LIGHT_GREEN,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successCheckmarkText: {
    fontSize: 40,
    color: COLORS.LIGHT_GREEN,
    fontWeight: 'bold',
  },
  successTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 30,
    textAlign: 'center',
  },
  successTxid: {
    fontSize: 13,
    color: COLORS.PRIMARY_BLUE,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    textAlign: 'center',
    marginBottom: 20,
  },

  // Lock Screen Styles
  lockScreen: {
    flex: 1,
    backgroundColor: COLORS.BLACK,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  lockIconArea: {
    marginBottom: 30,
    alignItems: 'center',
  },
  lockPasswordIcon: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockPasswordText: {
    fontSize: 32,
    color: COLORS.WHITE,
    fontWeight: 'bold',
    letterSpacing: 8,
    marginBottom: 8,
  },
  lockPadlock: {
    fontSize: 40,
    position: 'absolute',
    right: -25,
    top: -5,
  },
  lockTitle: {
    fontSize: 18,
    color: COLORS.WHITE,
    marginBottom: 30,
    textAlign: 'center',
  },
  faceIdButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginBottom: 40,
  },
  faceIdText: {
    fontSize: 18,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: '500',
    marginRight: 8,
  },
  faceIdArrow: {
    fontSize: 18,
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
  },
  lockPinError: {
    color: COLORS.BRIGHT_RED,
    fontSize: 14,
    marginBottom: 20,
    textAlign: 'center',
  },
  lockPinDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 50,
    gap: 15,
  },
  lockPinDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.MEDIUM_GRAY,
  },
  lockPinDotFilled: {
    backgroundColor: COLORS.WHITE,
  },
  lockKeypad: {
    width: '100%',
    maxWidth: 350,
  },
  lockKeypadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 30,
  },
  lockKey: {
    width: 75,
    height: 75,
    borderRadius: 37.5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  lockKeyText: {
    fontSize: 32,
    color: COLORS.WHITE,
    fontWeight: '300',
  },
  lockKeyDelete: {
    fontSize: 28,
    color: COLORS.WHITE,
    fontWeight: '300',
  },
  // Biometric Prompt styles
  biometricPromptModal: {
    backgroundColor: COLORS.VERY_DARK_GRAY,
    borderRadius: 20,
    padding: 30,
    width: '85%',
    maxWidth: 400,
  },
  biometricPromptTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 15,
    textAlign: 'center',
  },
  biometricPromptText: {
    fontSize: 16,
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 24,
  },
  biometricPromptButtons: {
    gap: 12,
  },
  biometricPromptButton: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  biometricPromptButtonYes: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  biometricPromptButtonNo: {
    backgroundColor: COLORS.OFF_WHITE,
  },
  biometricPromptButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.WHITE,
  },
  biometricPromptButtonTextNo: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.DARK_GRAY,
  },
});
export default styles;
