import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme';

export const quantaLinkStyles = StyleSheet.create({
  screen: {
    backgroundColor: COLORS.DARK_BG,
  },
  backButton: {
    position: 'absolute',
    left: 16,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  content: {
    flex: 1,
  },
  topHalf: {
    height: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 16,
  },
  bottomHalf: {
    height: '50%',
    paddingHorizontal: 16,
    paddingTop: 18,
    gap: 10,
  },
  connectedSummary: {
    width: '100%',
    alignItems: 'center',
    gap: 14,
    paddingTop: 8,
  },
  connectedTopSummary: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
  },
  connectedBadge: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(48, 209, 88, 0.24)',
    borderRadius: 999,
    backgroundColor: 'rgba(48, 209, 88, 0.1)',
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  connectedBadgeText: {
    color: COLORS.SUCCESS_GREEN,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    textAlign: 'center',
  },
  connectedMetric: {
    width: '100%',
    alignItems: 'center',
    gap: 3,
  },
  connectedStatusSlot: {
    width: '100%',
    justifyContent: 'center',
  },
  connectedAddressBox: {
    width: '100%',
    alignItems: 'flex-start',
    gap: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.045)',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  connectedPointsRow: {
    width: '100%',
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  connectedPointsIcon: {
    width: 28,
    height: 28,
  },
  connectedFullAddress: {
    width: '100%',
    color: COLORS.TEXT_SECONDARY,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'center',
  },
  connectedPointsValue: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 44,
    lineHeight: 50,
    fontFamily: 'CabinetGrotesk-Bold',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  connectedMetricLabel: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'center',
  },
  connectedStatsGrid: {
    width: '100%',
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  connectedStatBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 8,
  },
  connectedStatDivider: {
    width: 1,
    height: 44,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  connectedStatValue: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 22,
    lineHeight: 27,
    fontFamily: 'CabinetGrotesk-Bold',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  connectedStatLabel: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'center',
  },
  disconnectButton: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 69, 58, 0.26)',
    borderRadius: 999,
    backgroundColor: 'rgba(255, 69, 58, 0.08)',
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  disconnectButtonDisabled: {
    opacity: 0.62,
  },
  disconnectButtonText: {
    color: COLORS.ERROR,
    fontSize: 14,
    lineHeight: 17,
    fontFamily: 'CabinetGrotesk-Bold',
    textAlign: 'center',
  },
  disconnectButtonTextDisabled: {
    color: COLORS.TEXT_SECONDARY,
  },
  statusSlot: {
    width: '100%',
    height: 44,
    justifyContent: 'center',
  },
  title: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 26,
    lineHeight: 31,
    fontFamily: 'CabinetGrotesk-Bold',
    textAlign: 'center',
  },
  rewardChip: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    paddingHorizontal: 15,
    paddingVertical: 7,
  },
  rewardIcon: {
    width: 20,
    height: 20,
  },
  rewardText: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 17,
    lineHeight: 21,
    fontFamily: 'CabinetGrotesk-Bold',
    fontVariant: ['tabular-nums'],
  },
  addressBox: {
    width: '100%',
    alignItems: 'flex-start',
    gap: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.045)',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  addressLabel: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'CabinetGrotesk-Regular',
    textAlign: 'left',
  },
  addressValue: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
  },
  candidatePanel: {
    width: '100%',
    gap: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.045)',
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  candidatePanelTitle: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
  },
  candidateRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  candidateRowSelected: {
    borderColor: 'rgba(24, 88, 228, 0.62)',
    backgroundColor: 'rgba(24, 88, 228, 0.16)',
  },
  candidateCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  candidateTitle: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    textAlign: 'left',
  },
  candidateAddress: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: 'CabinetGrotesk-Regular',
    textAlign: 'left',
  },
  candidatePoints: {
    minWidth: 82,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
  },
  candidatePointsText: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    fontVariant: ['tabular-nums'],
    textAlign: 'right',
  },
  candidatePointsIcon: {
    width: 17,
    height: 17,
  },
  addressInput: {
    flex: 1,
    minHeight: 25,
    color: COLORS.TEXT_PRIMARY,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
    padding: 0,
  },
  errorText: {
    flex: 1,
    color: COLORS.ERROR,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
  },
  checkingText: {
    flex: 1,
    color: COLORS.TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
  },
  statusRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  successText: {
    flex: 1,
    color: COLORS.SUCCESS_GREEN,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
  },
  accountSwitchBanner: {
    width: '100%',
    minHeight: 38,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(245, 228, 162, 0.34)',
    borderRadius: 8,
    backgroundColor: 'rgba(245, 228, 162, 0.11)',
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  mismatchHelpBanner: {
    width: '100%',
    minHeight: 38,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 69, 58, 0.34)',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 69, 58, 0.1)',
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  accountSwitchText: {
    flex: 1,
    color: COLORS.YELLOW,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: 'CabinetGrotesk-Medium',
    textAlign: 'left',
  },
  inputRow: {
    width: '100%',
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pasteButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  connectButton: {
    width: '100%',
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  connectButtonDisabled: {
    backgroundColor: 'rgba(24, 88, 228, 0.28)',
  },
  connectButtonText: {
    color: COLORS.WHITE,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: 'CabinetGrotesk-Bold',
    textAlign: 'center',
  },
  connectButtonTextDisabled: {
    color: 'rgba(255, 255, 255, 0.46)',
  },
});
