import { StyleSheet } from 'react-native';
import { COLORS } from '../theme';
import { STATUS_BAR_HEIGHT, HORIZONTAL_PADDING, SCREEN_WIDTH } from './constants';

export const authStyles = StyleSheet.create({
  welcomeContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: 0,
    paddingBottom: HORIZONTAL_PADDING,
    backgroundColor: COLORS.DARK_BG,
  },
  welcomeContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  welcomeButtons: {
    width: '100%',
    paddingBottom: HORIZONTAL_PADDING + 20,
  },
  welcomeLogo: {
    width: 120,
    height: 120,
  },
  welcomeTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 8,
    textAlign: 'center',
    fontWeight: 'bold',
    paddingHorizontal: 12,
  },
  welcomeTagline: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 32,
    textAlign: 'center',
    fontWeight: '400',
    paddingHorizontal: 12,
  },
  passkeyButton: {
    backgroundColor: COLORS.PURPLE,
    marginTop: 8,
  },
  seedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SCREEN_WIDTH <= 375 ? 6 : 8,
  },
  seedBox: {
    width: '48%',
    backgroundColor: COLORS.CARD_BG,
    padding: SCREEN_WIDTH <= 375 ? 12 : 16,
    borderRadius: 8,
    marginBottom: SCREEN_WIDTH <= 375 ? 8 : 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seedNumber: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginRight: 8,
    minWidth: 20,
  },
  seedWord: {
    fontSize: SCREEN_WIDTH <= 375 ? 14 : 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  verifyBox: {
    marginBottom: 8,
  },
  verifyLabel: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  seedInput: {
    backgroundColor: COLORS.CARD_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    marginBottom: 16,
    textAlignVertical: 'top',
    minHeight: 100,
  },
  seedWordsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    marginBottom: 16,
    width: '100%',
  },
  seedWordContainer: {
    width: '47%',
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seedWordNumber: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    width: 20,
    textAlign: 'right',
    marginRight: 8,
  },
  seedWordInput: {
    flex: 1,
    backgroundColor: COLORS.CARD_BG,
    color: COLORS.VERY_LIGHT_GRAY,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY_BLUE,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
  },
  lockedContainer: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: HORIZONTAL_PADDING,
    paddingTop: HORIZONTAL_PADDING,
  },
  lockIconContainer: {
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 40,
  },
  lockIcon: {
    fontSize: 80,
    fontFamily: 'CabinetGrotesk-Regular',
    marginBottom: 20,
  },
  lockedText: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 12,
  },
  lockedSubtext: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    textAlign: 'center',
  },
  unlockButton: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
  },
  unlockButtonText: {
    color: COLORS.VERY_LIGHT_GRAY,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  pinButton: {
    backgroundColor: COLORS.MEDIUM_GRAY,
    marginTop: 16,
  },
  pinContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  pinTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    marginBottom: 12,
  },
  pinSubtext: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 20,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  pinError: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.DANGER_RED,
    marginBottom: 20,
    textAlign: 'center',
  },
  pinDotsContainer: {
    flexDirection: 'row',
    marginBottom: 50,
  },
  pinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: COLORS.BORDER_COLOR,
    marginHorizontal: 8,
  },
  pinDotFilled: {
    backgroundColor: COLORS.PRIMARY_BLUE,
    borderColor: COLORS.PRIMARY_BLUE,
  },
  pinKeypad: {
    width: '100%',
    maxWidth: 300,
  },
  pinRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  pinKey: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.DARK_BG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pinKeyText: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '600',
  },
  pinCancelButton: {
    marginTop: 20,
    paddingVertical: 16,
    alignItems: 'center',
  },
  pinCancelText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
    textAlign: 'center',
  },
  seedPhraseTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.DARK_GRAY,
    textAlign: 'center',
    marginBottom: 20,
  },
  seedPhraseWarning: {
    fontSize: 12,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.DANGER_RED,
    backgroundColor: COLORS.PINK_WHITE,
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    textAlign: 'center',
    lineHeight: 18,
  },
  // Lock Screen Styles
  lockScreen: {
    flex: 1,
    backgroundColor: COLORS.DARK_BG,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  lockIconArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 32,
  },
  lockPasswordIcon: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockPasswordText: {
    fontSize: 32,
    fontFamily: 'CabinetGrotesk-Bold',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: 'bold',
    letterSpacing: 8,
    marginBottom: 8,
  },
  lockPadlock: {
    fontSize: 40,
    fontFamily: 'CabinetGrotesk-Bold',
    position: 'absolute',
    right: -25,
    top: -5,
  },
  lockTitle: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 32,
    marginTop: 20,
    textAlign: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  faceIdButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 20,
    marginHorizontal: HORIZONTAL_PADDING,
  },
  faceIdText: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: '500',
    marginRight: 8,
  },
  faceIdArrow: {
    fontSize: 20,
    fontFamily: 'CabinetGrotesk-Medium',
    color: COLORS.PRIMARY_BLUE,
    fontWeight: 'bold',
  },
  lockPinError: {
    color: COLORS.BRIGHT_RED,
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Bold',
    marginBottom: 20,
    textAlign: 'center',
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  lockPinDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 50,
    gap: 16,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  lockPinDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.MEDIUM_GRAY,
  },
  lockPinDotFilled: {
    backgroundColor: COLORS.WHITE,
  },
  lockKeypad: {
    width: '100%',
    maxWidth: 352,
    marginBottom: 40,
    paddingHorizontal: HORIZONTAL_PADDING,
  },
  lockKeypadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 32,
  },
  lockKey: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  lockKeyText: {
    fontSize: 32,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  lockKeyIcon: {
    width: 24,
    height: 24,
    tintColor: COLORS.WHITE,
  },
  lockKeyCancelText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  lockKeyDelete: {
    fontSize: 28,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    fontWeight: '300',
  },
  // Biometric Prompt styles
  biometricPromptModal: {
    backgroundColor: COLORS.VERY_DARK_GRAY,
    borderRadius: 20,
    padding: 32,
    width: '85%',
    maxWidth: 400,
  },
  biometricPromptTitle: {
    fontSize: 24,
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 'bold',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 16,
    textAlign: 'center',
  },
  biometricPromptText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Regular',
    color: COLORS.VERY_LIGHT_GRAY,
    marginBottom: 25,
    textAlign: 'center',
    lineHeight: 24,
  },
  biometricPromptButtons: {
    gap: 12,
  },
  biometricPromptButton: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  biometricPromptButtonYes: {
    backgroundColor: COLORS.PRIMARY_BLUE,
  },
  biometricPromptButtonNo: {
    backgroundColor: COLORS.OFF_WHITE,
  },
  biometricPromptButtonText: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.VERY_LIGHT_GRAY,
  },
  biometricPromptButtonTextNo: {
    fontSize: 16,
    fontFamily: 'CabinetGrotesk-Medium',
    fontWeight: '600',
    color: COLORS.DARK_GRAY,
  },
});
